### ISSUE TITLE
RTP MIDI

### ISSUE THREAD

**Issue by tizi24** [rppicomidi/midi2usbhost#13]
It would be very interesting to add RTP MIDI capability to this project for MIDI output over WiFi using the Raspberry Pi Pico W

**Comment by rppicomidi** [comment]
@tizi24 My original intent for `midi2usbhost` was to "Make a Raspberry Pi Pico a USB Host to bridge modern USB MIDI to old school MIDI IN and MIDI OUT." The idea of this project is to make a simple plug and play device.

If you just want to make a USB MIDI device wireless, I already have a Pico W project, [ble-midi2usbhost](https://github.com/rppicomidi/ble-midi2usbhost), that provides a relatively low latency wireless connection between a USB MIDI device and a MIDI Bluetooth client in the central role.

All this said, I am interested in an abstract sense in RTP MIDI. Please explain your final application in detail so I may understand why adding RTP MIDI capability to this project is very interesting to you. I probably won't add it to this project, but I might create a new one if you make a good case.
