### ISSUE TITLE
Project based on RP2040, potential firmware target

### ISSUE THREAD

**Issue by DatanoiseTV** [rppicomidi/midi2usbhost#14]
Hey,

I am the guy behind the RP2040 based USB MIDI host and I am going to release it soon.
My plan is to make the firmware open, and I was thinking for compatibility reasons and community friendlyness,
it would be nice to base it on the midi2usbhost firmware.

![image](https://github.com/rppicomidi/midi2usbhost/assets/6614616/e74bbec9-7ec6-4fef-ae19-7cf43968e765)

![image](https://github.com/rppicomidi/midi2usbhost/assets/6614616/57a508d7-3f2f-4b51-94ad-54866923b39b)

@rppicomidi I am happy to send you a device if you would like one.
It is powered by USB-C, has TRS-A MIDI In and Out, a USB MUX, Power switch to external device via MOSFET and much more. Wriite me an E-Mail to midihost (at) datanoise.org

**Comment by rppicomidi** [comment]
@DatanoiseTV Exciting news. I will leave this issue open for a while in case anyone will prefer your product to DIY.

**Comment by rppicomidi** [comment]
@DatanoiseTV I hope you had a good year. I will close this issue today.
