### ISSUE TITLE
Pico PIO USB Host

### ISSUE THREAD

**Issue by Colatino** [rppicomidi/midi2usbhost#3]
Hi!
Not really an issue but arduino-pico, tinyUSB and Adafruit-tinyUSB just got updated to oficially support USB hosting with PIO on the RP2040. 
Maybe that can be a shortcut to get MIDI hosting working.

**Comment by rppicomidi** [comment]
Thanks @Colatino Using PIO for USB is very interesting. However, if you use the code as described in this project with my forked tinyusb, MIDI hosting is working. It uses the built-in USB IP, not PIO. You can't hook the MIDI device to the Pico host through a hub with this code though. I am waiting for my pull request to the tinyusb  project to be merged to the tinyusb master branch. There has been a bit of activity on the host side of that project recently, so maybe my code will get merged eventually.

**Comment by fadh3r** [comment]
Same here - could not compile with your instructions...

**Comment by fadh3r** [comment]
I've got an error #include "class/midi/midi_host.h"

**Comment by AshuSharda** [comment]
> https://github.com/csBlueChip/tinyusb/tree/master/src/class/midi take a look at this file with this got almost 90 % of compilation but then getting error please let me know if you are able to get it to work.

**Comment by rppicomidi** [comment]
@fadh3r Please see my comments on issue #4 @Colatino I have never used the Arduino toolchain so I cannot comment.

**Comment by fadh3r** [comment]
@rppicomidi by your readme.md I've got an error on stage:
'git clone --recurse-submodules https://github.com/midiusb2host.git'
with error
'Cloning into 'midiusb2host'...
remote: Not Found
fatal: repository 'https://github.com/midiusb2host.git/' not found
'''
so, this typo is fixing by adding right link to your github profile(name is missing in current command line)
'https://github.com/rppicomidi/midi2usbhost'

and I'm getting many different errors with include using current pico-sdk...

**Comment by fadh3r** [comment]
```
[cmake] Using board configuration from /home/jj/_last_Pico_rppicomidi/pico-sdk/src/boards/include/boards/pico.h
[cmake] CMake Error at /home/jj/_last_Pico_rppicomidi/pico-sdk/src/CMakeLists.txt:23 (add_subdirectory):
[cmake]   add_subdirectory given source "tinyusb" which is not an existing directory.
[cmake] Call Stack (most recent call first):
[cmake]   /home/jj/_last_Pico_rppicomidi/pico-sdk/src/rp2_common/CMakeLists.txt:58 (pico_add_subdirectory)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "/home/jj/_last_Pico_rppicomidi/midi2usbhost/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "/home/jj/_last_Pico_rppicomidi/midi2usbhost/build/CMakeFiles/CMakeError.log".
```

**Comment by rppicomidi** [comment]
@fadh3r Thank you for finding typos and omissions in the build instructions. Please try the latest README.md file. As you pointed out, the path to the project code was wrong. More important, the instructions for using the forked tinyusb should have made clear you have to set the current directory to pico-sdk/lib/tinyusb first before you checkout the origin/midihost branch. Finally, I added instructions for a command line build. It assumes that the toolchain is installed correctly. I hope that helps.

**Comment by fadh3r** [comment]
I'm very appreciated to you, @rppicomidi! I'll try it! Thanks!

**Comment by MickeyDelp** [comment]
@rppicomidi Thanks for the doc updates. I've got it working now too. 
One thing I notice is that when a USB device is not connected, there is a constant stream of garbage MIDI out of the UART. Are you seeing that too or is it just my setup?

**Comment by rppicomidi** [comment]
@MickeyDelp I don't have this setup connected at the moment. I don't recall this being an issue. May I ask that if the problem persists that you file a new Issue here? If others are seeing the same issue they might find the solution.

**Comment by rppicomidi** [comment]
@Colatino Are you able to build the code now that I corrected typos and omissions in the README.md file? If so, do you mind if I close this issue? Adding MIDI Host support to PIO USB is a different project in my opinion.

**Comment by Colatino** [comment]
I couldn't build it but my problem is the toolchain... for some reason it doesn't install properly.

You can close the issue, I opened it with the intent to sugest a new feature to the project but I'm a github noob and don't know how to.

**Comment by MickeyDelp** [comment]
> @MickeyDelp I don't have this setup connected at the moment. I don't recall this being an issue. May I ask that if the problem persists that you file a new Issue here? If others are seeing the same issue they might find the solution.

It was just a noisy connection. I solved it by using a series diode on the UART TX. I would set that pin to open drain for MIDI, but the Pico does not seem to have that option.

**Comment by rppicomidi** [comment]
@MickeyDelp I am glad your issue is solved. I am going to close this issue.

**Comment by fadh3r** [comment]
Builded successfully!
Thank you @rppicomidi

**Comment by rppicomidi** [comment]
@Colatino  I reopened this issue to let you know I did in fact implement PIO USB MIDI Host and generated a new project in my repo called [pico-usb-midi-filter](https://github.com/rppicomidi/pico-usb-midi-filter), which uses the PIO USB MIDI host and the built-in USB MIDI port as a MIDI device to create a MIDI message filter. The README for that project is hopefully enough better that you are able to built that project.  Thank you for calling the Pico-PIO-USB project to my attention.

**Comment by Colatino** [comment]
That's great! I'll have a look as soon as possible.

**Comment by AndrewCapon** [comment]
> Thanks @Colatino Using PIO for USB is very interesting. However, if you use the code as described in this project with my forked tinyusb, MIDI hosting is working. It uses the built-in USB IP, not PIO. You can't hook the MIDI device to the Pico host through a hub with this code though. I am waiting for my pull request to the tinyusb project to be merged to the tinyusb master branch. There has been a bit of activity on the host side of that project recently, so maybe my code will get merged eventually.

Hi There,

Why is there the restriction to not using hubs, is this a TinyUSB thing?

Many thanks for any info

Andy

**Comment by rppicomidi** [comment]
@AndrewCapon There is a bug somewhere in my tinyusb fork's implementation of the MIDI Host code that breaks hubs, I believe. However, there is a new midihost tinyusb pull request #1627 based on my code and a better implementation of USB host bulk endpoint support. Maybe @atoktoto got it working. I haven't had time to test it yet.

**Comment by AndrewCapon** [comment]
Hi @rppicomidi,

Thanks for the info. 

I have tried the @atoktoto one as well, it has the same issue unfortunately.

I will take it up on #1627.

All the best, and thanks for the MIDI hosting code.

Andy

**Comment by AndrewCapon** [comment]
Thanks for the info, If I get some time I will have a look, maybe another set of eyes may see something.

I had a quick look and from what I remember there is an enumeration for the hub, then for the first device plugged into the hub, but from that point on if you add a device it doesn't enumerate.

Also the disconnect only happens if you remove the hub, removing the device from the hub doesn't fire this.

Does this sound about right?

**Comment by rppicomidi** [comment]
@AndrewCapon Yes, that's about right. It's weird because hubs work fine for MSC, which is not all that different from MIDI in that they both use 2 bulk endpoints.
