### ISSUE TITLE
Can't find #include "class/midi/midi_host.h"

### ISSUE THREAD

**Issue by AshuSharda** [rppicomidi/midi2usbhost#4]
Hi 👋 
I was trying to compile your code on a windows 10 with  
vs code but I was not able find this file anywhere in your code (#include"class/midi/midi_host.h") can you please guide me about this issue. I have old m audio keystudio 49 that doesn't connects to Cubasis 3 but works fine with FL studio mobile on the same phone. Thanks in advance. I am getting the same error as described by fadh3r please help

**Comment by rppicomidi** [comment]
@Sorry for the slow reply. The file is in my fork of the tinyusb library in the midihost branch. https://github.com/rppicomidi/tinyusb/tree/midihost/src/class/midi. So either your PC's pico sdk has the wrong fork of tinyusb in it, or the tinyusb fork has the wrong branch checked out. Please see the [README.md](https://github.com/rppicomidi/midi2usbhost#using-the-forked-tinyusb-libraryl) for step by step.

**Comment by AshuSharda** [comment]
Hi first of all thank you very much for replying. I was able to compile the code correctly after getting the library in midi host branch you mentioned. Well for software part I think I have done it. Now I will connect to my m audio keystudio tomorrow and let you know if it is working. Thanks again. 🙏

**Comment by AshuSharda** [comment]
@rppicomidi I fixed the issue of notes getting stuck it had nothing to with raspberry pi pico midi2usbhost. It was the ble parser board which had the problem in its code. Thanks again for your help.
