### ISSUE TITLE
Capturing incoming midi pitch bend messages

### ISSUE THREAD

**Issue by Terumi** [rppicomidi/midi2usbhost#8]
Hello.
I can capture midi notes with velocity and modulation from my arturia microlab. but I the pitch bend messages, as soon as I take my hands of the pitch bend strip, seem to freeze my pico.
Is this an know issue?

**Comment by rppicomidi** [comment]
This is not a known issue. Thank you for reporting the bug. Please tell me what is the git hash for midi2usbhost, the tinyusb library, and the pico-sdk. I have the Arturia Keylab Essential  88 keyboard so maybe I can reproduce it.

**Comment by Terumi** [comment]
I found it:
I had a printf here:
if (status & UART_UARTMIS_TXMIS_BITS)
    {
        // ready to transmit
        uint8_t val;
        RING_BUFFER_SIZE_TYPE npopped = ring_buffer_pop_unsafe(&midi_uart->midi_uart_tx, &val, 1);
        if (npopped == 0)
        {
            // No data to send; disable the interrupt
            uart_set_irq_enables(midi_uart->midi_uart, true, false);
        }
        else
        {
            // send the byte
            **//printf(val + "\r\n");**
            uart_get_hw(midi_uart->midi_uart)->dr = val;
        }
    }


and that was ruining the program.
Sorry about that :)

**Comment by rppicomidi** [comment]
@Terumi No problem. Please do report any other issues if you find them or request help here if you need it.
